# Generated by Django 3.2.7 on 2021-09-28 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_cls_name_subject_cls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cls_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class'),
        ),
    ]
