# Generated by Django 3.2.7 on 2021-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_subject_cls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cls_id',
            field=models.CharField(max_length=100),
        ),
    ]
